---
title: "Fig 3"
author: "Ning Chin"
date: "8/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

Setup
```{r setup, warning = FALSE, message = FALSE}
library(phyloseq)
library(ggplot2)
library(ggrepel)
library(vegan)
library(tidyr)
library(cowplot)
library(qvalue)
library(kableExtra)

set.seed(7)

set.color <- as.character(c("#DD1717", "#000249", "#FF4949", "#0F4392", 
                            "#FCCDE5", "#8DD3C7", "#FFFFB3", "#80B1D3", "#FB8072", "#BC80BD",
                            "#FFED6F", "#D9D9D9", "#BEBADA", "#CCEBC5", "#FDB462", "#B3DE69"))
names(set.color) <- c("NEG", "POS", "prev", "posv",
                      "Actinobacteria", "Bacteroidetes", "Cyanobacteria", "Elusimicrobia", "Fibrobacteres", "Firmicutes",
                      "Proteobacteria", "Spirochaetes", "Tenericutes", "TM7", "Verrucomicrobia", "WPS-2")

theme_set(theme_grey()+
            theme(panel.grid = element_blank(),
                  panel.background = element_blank(),
                  panel.border = element_rect(fill = NA, colour = "black", size = 0.2),
                  axis.title = element_text(size = 10),
                  axis.text = element_text(size = 6),
                  axis.line = element_line(color = "black", size = 0.2),
                  legend.title = element_text(size = 8, face = "bold"),
                  legend.text = element_text(size = 6),
                  legend.key = element_blank(),
                  legend.key.size = unit(10, "pt")))

cmv_score <- readRDS("cmv_score.RData")
```

## Filtering
```{r filt}
filterfunc <- function(psobj, prevpercent, maxpercent) {
  ps0 <- subset_taxa(psobj, !is.na(Phylum))
  ps1 <- tax_glom(ps0, "Genus", NArm = TRUE)
  prevalence <- apply(otu_table(ps1), 2, function(x) sum(x > 0)/nsamples(ps1))
  maxpercentage <- apply(otu_table(ps1), 1, function(x) x/sum(x)*100)
  maxpercentage <- apply(maxpercentage, 1, function(x) max(x))
  keepTaxa <- names(prevalence)[(prevalence >= prevpercent & maxpercentage > maxpercent)]
  ps2 <- prune_taxa(keepTaxa, ps1)
  return(ps2)
}

ps0 <- readRDS("../phyloseq_GG_tree_190304.RData")
ps <- filterfunc(ps0, 0.05, 0.01)
ps.log <- transform_sample_counts(ps, function(x) log2(x + 1))
mtdata <- read.csv("../metadata.csv", stringsAsFactors = TRUE)

imm <- read.csv("../cor_w_immune/190627_CUR01_immune_data.csv", row.names = 1)
immlabs <- read.delim("../211202 pretty_labels_imm.txt")

# rearrange colnames based on cell type using pre-arranged txt
imm <- imm[,immlabs$imm]
colnames(imm) <- immlabs$label
```

## Fig 3A. PCA of immunnophenotypes
```{r 3a}
pca <- prcomp(imm, scale. = TRUE)
out <- cbind(mtdata, as.data.frame(pca$x))
percentage <- round(pca$sdev^2 / sum(pca$sdev^2) * 100, 2)

eu <- dist(imm)
imm.label <- paste0("P = ", round(adonis(eu ~ CMV, data = out, method = "eu")$aov.tab$`Pr(>F)`[1],3))

# beta-dispersion p-value
round(permutest(betadisper(eu, mtdata$CMV))$tab$`Pr(>F)`[1], 3)

toploadings <- c("CD4 naïve", "KI67+, CD4", "IL4+, CD4",
                 "IL17+, CD4mem", "IL4+, CD8",
                 "CD8 naïve", "KI67+, CD8", "CD8 effector",
                 "CD56-CD16+, NK cells",
                 "CD83+, monocytes", "NK-CTL")

mult <- min(max(pca$x[,1]) - min(pca$x[,1]) / max(pca$rotation[,1]) - min(pca$rotation[,1]),
            max(pca$x[,2]) - min(pca$x[,2]) / max(pca$rotation[,2]) - min(pca$rotation[,2]))

loading <- data.frame(marker = toploadings,
                      PC1 = mult*pca$rotation[toploadings,1],
                      PC2 = mult*pca$rotation[toploadings,2])

fig3a <- ggplot(out, aes(x = PC1, y = PC2)) +
  geom_segment(data = loading, aes(x = 0, y = 0, xend = PC1, yend = PC2),
               color = "darkgrey", arrow = arrow(length = unit(0.2, "cm")), alpha = 0.8) +
  geom_label_repel(data = loading, aes(label = marker), size = 2) +
  geom_point(alpha = 0.6, aes(color = CMV), size = 1.5) +
  labs(x = paste("PC1 (", percentage[1], "%)", sep = ""),
       y = paste("PC2 (", percentage[2], "%)", sep = "")) +
  scale_color_manual(name = "RhCMV", values = set.color, limits = force) +
  theme(panel.border = element_rect(fill = NA, colour = "black", size = 0.2),
        aspect.ratio = 1,
        legend.position = c(1,0),
        legend.justification = c(1,0),
        legend.background = element_rect(color = "black", size = 0.2),
        legend.spacing.y = unit(1, "pt"),
        legend.margin = margin(2, 2, 0, 2),
        plot.margin = unit(c(2, 2, 2, 2), "pt")) +
  annotate("text",  x = Inf, y = Inf, fontface = "italic",
           vjust = 1.4, hjust = 1.1, 
           size = 2,
           label = imm.label)
fig3a
```

## Fig 3B. CMV-microbial score correlates with immune markers
```{r 3b, warning = FALSE}
# without stratifying
corre <- data.frame(marker = colnames(imm),
                    rho = apply(imm, 2, function(x) cor.test(x, cmv_score, method = "spearman")$estimate),
                    p = apply(imm, 2, function(x) cor.test(x, cmv_score, method = "spearman")$p.value))
corre$q <- qvalue::qvalue(corre$p, pi0 = 1)$qvalues
corre <- corre[order(corre$p),]
kable(corre[corre$q < 0.05,], row.names = 0) %>% kable_styling()

#write.csv(corre[corre$q < 0.05,], "211201_sup_table1.csv", row.names = FALSE)

# look at the list and pick the ones that are most significant - there are some redundant ones so
intimm <- c("CD83+, monocytes", "NK-CTL", "IL4+, CD4", "KI67+, CD8", "CD8 effector", "IL4+, CD8")

corre.sig <- dplyr::left_join(data.frame(marker = intimm), corre, by = "marker")
corre.sig$marker <- factor(corre.sig$marker, levels = intimm)
corre.sig$label <- paste0("Padj < 0.05\nrho = ", round(corre.sig$rho, 2))

long <- data.frame(mtdata, cmv_score, imm[,intimm], check.names = FALSE)
long <- pivot_longer(long, all_of(intimm), names_to = "marker", values_to = "imm")
long$marker <- factor(long$marker, levels = intimm)

fig3b <- ggplot(long, aes(x = s1, y = imm)) +
  geom_smooth(method = lm, se = FALSE, color = "darkgrey", size = 0.75) +
  geom_point(shape = 1, size = 0.5) +
  facet_wrap(~marker, scale = "free", nrow = 2) +
  scale_color_manual(values = set.color) +
  geom_text(data = corre.sig, aes(label = label, x = -Inf, y = Inf, vjust = 1.1, hjust = -0.05), size = 2, fontface = "italic") +
  labs(x = "CMV-microbial score", y = "Frequency (%)") +
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, margin = margin(0, 0, 2, 0, "pt")),
        legend.position = "none",
        panel.border = element_rect(fill = NA, colour = "black", size = 0.2),
        aspect.ratio = 1,
        plot.margin = unit(c(2, 2, 2, 10), "pt"))
fig3b
```


## Put all plots together
```{r fig3, fig.show = "hide"}
plot_grid(fig3a, fig3b, labels = c("A", "B"), nrow = 1, label_size = 16, hjust = -0.1, vjust = 1.1, rel_widths = c(1, 1.5))

ggsave("211112_fig3.pdf", width = 6.8, height = 2.8, units = "in", device = "pdf")

sessionInfo()
```